export const ALERT_TYPES = ['SOS', 'THREAT', 'HARASSMENT', 'OTHER'];
export const ALERT_STATUS = ['ACTIVE', 'RESOLVED', 'CANCELLED'];
export const INCIDENT_TYPES = ['HARASSMENT', 'ASSAULT', 'THEFT', 'THREAT', 'UNSAFE_AREA', 'OTHER'];
export const COMMUNITY_ALERT_TYPES = ['WARNING', 'SAFE_ZONE', 'INFO'];
